### ISSUE TITLE
Not working with Gnome Shell 3.1.90+

### ISSUE THREAD

**Issue by wavded** [joufella/gnome-shell-extension-hamster#1]
The reason:

> The API has changed. The extensions need a new init(), enable() and disable() functions. Presumably the intention is so that they can be started / stopped without restarting the shell. You either need to wait for the extensions to be updated, or do some fairly minor js hacking. The gnome-shell git repo has working examples. 

Comment made from article (http://www.webupd8.org/2011/09/gnome-shell-make-applications-start-on.html)

Can this be fixed?

**Comment by ghost** [comment]
I made some correction for gnome-shell-3.2, see http://dl.dropbox.com/u/9509772/hamster-se-gs3.2.diff
